[package]
name = "rcgpar"
version = "0.1.0"
edition = "2024"
authors = [
    "Tommi Mäklin <tommi@maklin.fi>",
    "Jarno N. Alanko <alanko.jarno@gmail.com>",
    "Joel Pietiläinen <joel.pietilainen@helsinki.fi>",
]
description = "Riemannian conjugate gradient descent for estimating mixture model weights."
readme = "README.md"
homepage = "https://github.com/tmaklin/rcgpar"
repository = "https://github.com/tmaklin/rcgpar"
license = "LGPL-2.1-or-later"

[features]
wgpu = ["burn/wgpu"]
webgpu = ["burn/webgpu"]
vulkan = ["burn/vulkan"]

[dependencies]
burn = { version = "0.19", default-features = false, features = ["ndarray"] }
burn-tensor = "0.19"
num = "0.4"
statrs = "0.18"

[dev-dependencies]
assert_approx_eq = "1.1"
